import { defineConfig } from '@playwright/test';
export default defineConfig({
  testDir: './tests/integration/p18',
  testMatch: '**/*.spec.ts',
  globalTeardown: './tests/integration/p18/teardown.mjs',
  workers: 1,
  fullyParallel: false,
  timeout: 120000,
  retries: 0,
  expect: { timeout: 15000 },
  reporter: [['list'], ['json', { outputFile: 'docs/verification/P18/browser-results.json' }]],
  use: {
    baseURL: 'http://127.0.0.1:5381',
    headless: true,
    viewport: { width: 1440, height: 1050 },
    locale: 'ar-EG',
    timezoneId: 'Africa/Cairo',
    reducedMotion: 'reduce',
    trace: 'off',
    screenshot: 'off',
  },
  webServer: {
    command: 'node --import tsx tests/integration/p18/serve.ts',
    env: { TSX_TSCONFIG_PATH: 'tsconfig.base.json' },
    url: 'http://127.0.0.1:4382/health',
    reuseExistingServer: false,
    timeout: 180000,
    gracefulShutdown: { signal: 'SIGTERM', timeout: 45000 },
  },
});
