import { defineConfig } from 'vitest/config';
export default defineConfig({
  test: {
    include: [
      'tests/integration/p25/**/*.db.test.ts',
      'tests/integration/p24/**/*.db.test.ts',
      'tests/integration/p23/**/*.db.test.ts',
      'tests/integration/p22/**/*.db.test.ts',
      'tests/integration/p21/**/*.db.test.ts',
      'tests/integration/p20/**/*.db.test.ts',
      'tests/integration/p19/**/*.db.test.ts',
      'tests/integration/p18/**/*.db.test.ts',
      'tests/integration/p17/**/*.db.test.ts',
      'tests/integration/p16/**/*.db.test.ts',
      'tests/integration/p15/**/*.db.test.ts',
      'tests/integration/p14/**/*.db.test.ts',
      'tests/db/**/*.test.ts',
      'tests/integration/p11/**/*.db.test.ts',
      'tests/integration/p12/**/*.db.test.ts',
      'tests/integration/p13/**/*.db.test.ts',
    ],
    environment: 'node',
    passWithNoTests: false,
    fileParallelism: false,
    maxWorkers: 1,
    testTimeout: process.env['SHAHN_TEST_PG_BIN'] ? 90000 : 30000,
    hookTimeout: 90000,
    reporters: ['default'],
  },
});
